<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <AssemblyName>CornDownloader</AssemblyName>
    <RootNamespace>CornDownloader</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <Optimize>true</Optimize>
    <AllowUnsafeBlocks>false</AllowUnsafeBlocks>
    <Company>ConnorCorn07</Company>
    <Product>Corn Downloader</Product>
    <Description>Zero-dependency Windows app downloader and installer by Corn Studios</Description>
    <Copyright>2025</Copyright>
    <Version>1.1.0</Version>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

</Project>